"""Render corrections.md from verified_values.jsonl."""

import json
from pathlib import Path

IN = "/home/shawn/Code/inscriptions/runs/2026-04-23-descriptive-stats/verifier-work/verified_values.jsonl"
OUT = "/home/shawn/Code/inscriptions/runs/2026-04-23-descriptive-stats/outputs/corrections.md"

rows = [json.loads(line) for line in open(IN)]

counts = {"yes": 0, "tolerance": 0, "no": 0}
for r in rows:
    counts[r["match"]] = counts.get(r["match"], 0) + 1

# Compose file
lines = []
lines.append("# Corrections audit — LIRE v3.0 descriptive profile (2026-04-23)")
lines.append("")
lines.append("_Generated by `data-profile-verifier` methodology (adversarial re-check against source parquet)._")
lines.append("")
lines.append("## Summary")
lines.append("")
lines.append(f"- Total claims audited: **{len(rows)}**")
lines.append(f"- Exact match (`yes`): **{counts.get('yes', 0)}**")
lines.append(f"- Within tolerance (`tolerance`): **{counts.get('tolerance', 0)}**")
lines.append(f"- Divergent / failed (`no`): **{counts.get('no', 0)}**")
lines.append("")
lines.append("All numerical claims reproduce within the tolerances specified in the brief "
             "(exact for counts, ±0.1 pp for percentages, ±0.5 % for chi-square, ±0.1 % for floats). "
             "See `verdict.md` for the overall verdict and semantic-dependency notes "
             "(proposer Decisions 1–6).")
lines.append("")
lines.append("## Semantic dependencies on proposer decisions")
lines.append("")
lines.append("The following numerical claims depend on judgement calls the proposer recorded "
             "in `decisions.md`. The numbers reproduce under the scout's stated semantics; "
             "re-interpreting the semantics will change the numbers.")
lines.append("")
lines.append("| claim_id | semantic dependency | notes |")
lines.append("|---|---|---|")
lines.append("| c0001 | Decision 2 (row count 182,853 vs brief-expected 182,852) | "
             "Reproduced exactly at 182,853; brief expectation off by 1. |")
lines.append("| c0002, c0004, all null-rate claims | Decision 3 (parquet has 63 of the 66 "
             "schema columns) | Column count reproduces; "
             "the three missing columns (`is_geotemporal`, `is_within_RE`, `material_EDCS`) "
             "are correctly absent and so `is_within_RE-rate`, `is_geotemporal-rate` artefact "
             "checks are correctly marked NOT RUN. |")
lines.append("| c0169, c0170, c0171 | Decision 4 (temporal-outliers is a literal "
             "endpoint-outside-range count, not a non-overlap count) | Verifier confirms "
             "the literal counts (1,949 / 32,615 / 34,562) reproduce exactly. Verifier also "
             "independently confirms the overlap interpretation: every row (182,853 / 182,853) "
             "has a date-interval that overlaps 50 BC – AD 350, so under an overlap filter the "
             "'outlier' count would be 0, not 34,562. The 34,562 figure reflects data-quality "
             "endpoint issues (e.g. `not_after == 2230`), not envelope violations. |")
lines.append("| c0203–c0216 (granularity categories) | Decision 5 (granularity peaks flagged "
             "at >5 % threshold) | All counts and percentages reproduce. "
             "Cosmetic/semantic issue: the claim descriptions say the "
             "`other_round_values` bucket is \"10,20,30,...,500\" (implying every multiple "
             "of 10 up to 500), but the scout's code hardcodes a discrete set "
             "`{10,20,30,40,60,70,75,80,90,125,150,175,250,300,400,500}` (16 values; "
             "skips 100/200/350/450 etc., includes 75/125/175 which are not multiples of 10). "
             "Number 3,971 is correct relative to the code; the description is misleading. "
             "Recommend proposer edit description to enumerate the discrete set. |")
lines.append("| c0108–c0111, c0136–c0139 (editorial-spikes at year 97) | Decision 6 (year 97 "
             "is a dip not a spike) | Counts and chi-square values reproduce exactly. "
             "Proposer correctly reported direction-agnostic statistics. |")
lines.append("")
lines.append("## Independent cross-checks")
lines.append("")
lines.append("Spot-checks performed with independent code paths (numpy-based frequency "
             "dictionaries rather than scout's pandas boolean indexing):")
lines.append("")
lines.append("- **Dataset-level null-rate** (random column `inscr_process`): 93.8683 % — "
             "matches scout (±0.0000 pp). PASS.")
lines.append("- **Province spot check** (random top-20: `Roma`): count=65,457, "
             "lat_null=0 %, not_before_null=0 %. PASS.")
lines.append("- **Urban-area spot check** (random top-20: `Cirta`): count=1,020, "
             "lat_null=0 %, not_before_null=0 %. PASS.")
lines.append("- **Granularity histogram** (numpy.unique frequency table): all 7 bucket "
             "counts match exactly. PASS.")
lines.append("- **Broad date-range histogram** (independent frequency dict): all 7 buckets "
             "match exactly. PASS.")
lines.append("- **Midpoint-inflation** (at AD 50, 150, 250, 350): all at-year counts, "
             "off-year counts, and chi-square values match exactly. PASS.")
lines.append("- **Editorial-spikes** (all 14 year/column combinations): all at-year counts, "
             "neighbour means, and chi-square values match exactly. PASS.")
lines.append("- **Decision-4 overlap hypothesis**: 182,853 / 182,853 rows overlap the "
             "50 BC – AD 350 envelope. Confirms the scout's interpretation that the "
             "'34,562 outliers' figure reflects endpoint extremes, not rows outside the "
             "envelope. PASS.")
lines.append("")
lines.append("## Full claim-by-claim audit")
lines.append("")
lines.append("Columns: `claim_id` | `description` | `scout_value` | `my_value` | `match` | `notes`.")
lines.append("")
lines.append("| claim_id | description | scout | verifier | match | notes |")
lines.append("|---|---|---|---|---|---|")


def fmt_val(v):
    if isinstance(v, dict):
        return (
            f"rank={v.get('rank')}, group=`{v.get('group')}`, count={v.get('count')}"
        )
    if isinstance(v, float):
        # preserve precision but avoid trailing noise
        s = f"{v:.6g}"
        return s
    return str(v)


def esc(s):
    # Escape pipes for markdown tables
    return s.replace("|", "\\|")


for r in rows:
    lines.append(
        f"| {r['claim_id']} | {esc(r['description'])} | "
        f"{fmt_val(r['scout_value'])} | {fmt_val(r['my_value'])} | "
        f"{r['match']} | {esc(r['notes'])} |"
    )

Path(OUT).write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
print(f"total claims: {len(rows)}; yes={counts['yes']}, tolerance={counts['tolerance']}, no={counts['no']}")
