name: inscriptions-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - fastparquet
  - tempun
  - scikit-learn
  - scipy
  - pyarrow
  - os
  - re
  - hashlib
  - tqdm
